---
version: "3"
services:
 devopsdb:
   container_name: devopsdb
   image: ramakrishna737/app1:webdb
   ports:
     - "3306:3306"

 application:
   container_name: appcontainer
   image: ramakrishna737/app1:webapp
   ports:
     - "1234:8080"
   depends_on:
     - "devopsdb"
